---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: install tomcat
    apt: name=tomcat state=present
  - name: start tomcat
    service: name=tomcat state=started
  - name: install docker
    apt: name=docker state=present
  - name: start docker
    service: name=docker state=started
  - name: install git
    apt: name=git state=present
  - name: get repo
    git: repo=https://github.com/hermann1990/webappdeploy.git dest=/tmp/githurepo
  - name: Build Dockerfile
    command: chdir=/tmp/githurepo docker build -t addressbook:ansible .
  - name: run Image
    command: docker run -itd -P addressbook:ansible
